name = "SciAlgs"
uuid = "a96222a4-04e9-11ea-3d18-e1c1364290fa"
authors = ["Daniel Menendez Crespo <danielmail7@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
