[package]
name = "julia_call_rust"
version = "0.1.0"
authors = ["Daniel Menendez Crespo <danielmail7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "my_rust_lib"
crate-type = ["dylib"]
